# In ansible "when" is the conditional keyword that is used to define a condition on the basis of which a task gets executed

---
- name: install apache in all systems using condition
  hosts: all
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat" # this task will execute only when os is RedHat(Rhel)
      notify: start httpd

    - name: install apache2
      apt:
        name: apache2
        state: present
      when: ansible_os_family== "Debian"      # this task will execute only when os is debian(Ubuntu)
      notify: start apache2
    
    - name: copy index.html file    # encorporating the copy module to copy the index.html 
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/html
        mode: 0666
  
  handlers:
    - name: start httpd
      service:
        name: httpd
        state: started
    - name: start apache2
      service:
        name: apache2
        state: started