---
- name: Copy module
  hosts: all
  become: true
  tasks:
    - name: copy a file
      copy:
        src: /home/ansadmin/index.html
        dest: /home/ansadmin
        mode: 0600 # this is the permission
        owner: John   # we have already created the user john so we are giving the ownership to it. Else the ownership will remain root

# command to run:  ansible-playbook -i hosts copyFile.yaml
