# lists and with_items are used to install multiple packages in a single task.
# with_items is depriciated now so it is recomended to use lists 

---
- name: install multiple packages
  hosts: Webservers
  become: true
  tasks:
    - name: install packages
      yum:
        #name: ['git','tree','make','gzip','gcc','wget','telnet']    # this is the list way of writing package names
        name: "{{ item }}"
        state: installed
      loop:
        - git
        - tree
        - make
        - gzip
        - gcc
        - wget
        - telnet