-
  name: Deploy a web application
  hosts: db_and_web_server
  tasks:
    - name: Install dependencies
      apt: name={{ item }} state=present
      with_items:
       - python
       - python-setuptools
       - python-dev
       - build-essential
       - python-pip
       - python-mysqldb
    # Task 3
    - name: MySQL database
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - mysql-client

#Task 4
    - name: start mysql service
      service:
        name: mysql
        state: started
        enabled: yes      # enabled is set to yes so that it can start when system restarts