- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: sample ec2 key
      ec2_key:
        name: sample-key
        region: us-east-2
      register: keyout
    - name: debugging  
      debug:
        var: keyout
