- name: Ubuntu_instance
  ec2:
    region: "{{ region }}"
    key_name: "{{ key_pair }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_ubuntu }}"
    group_id: "{{ security_group }}"
    vpc_subnet_id: "{{subnet}}" 
    count: 1
    wait: true
    assign_public_ip: true
  register: ubuntu_inst
  ignore_errors: true

- name: debugging
  debug:
    var: ubuntu_inst

- name: Add Ubuntu Instance to Host Group
  add_host:
    name: "{{ item.instances[0].public_ip }}"
    groups: ubuntu_instances
  with_items: "{{ ubuntu_inst.tagged_instances }}"
  when: ubuntu_inst.changed

- name: Wait for SSH to be available on Ubuntu Instance
  wait_for:
    host: "{{ item.instances[0].public_ip }}"
    port: 22 #opening the SSH port for the server
    timeout: 300
  with_items: "{{ ubuntu_inst.tagged_instances }}"
  when: ubuntu_inst.changed

# trying for Windows instance

- name: Launch Windows Instance
  ec2:
    region: "{{ region }}"
    key_name: "{{ key_pair }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_windows }}"
    group_id: "{{ security_group }}"
    vpc_subnet_id: "{{subnet}}"
    count: 1
    wait: true
    assign_public_ip: true
  register: windows_inst

- name: debugging windows
  debug:
    var: windows_inst
  

  ###    Completed upto Launching the servers . Tomorrow perform linux operatons etc..