---
# tasks file for aws_instances
- name: Ubuntu_instance
  ec2:
    region: "{{region}}"
    key_name: "{{key_pair}}"
    instance_type: "{{instance_type}}"
    image_id: "{{ami_ubuntu}}"
    security_group: "{{security_group}}"
    count: 1
    wait: true
    assign_public_ip: true
  register: ubuntu_inst

- name: debugging
  debug: 
    var: ubuntu_inst
