---
- name: Stop and remove httpd and apache2 services from RHEL and Ubuntu servers
  hosts: all
  become: true
  tasks:
    - name: stop httpd
      service:
        name: httpd
        state: stopped
      when: ansible_os_family=="RedHat"
      notify: uninstall httpd
    
    - name: stop apache2
      service: 
        name: apache2
        state: stopped
      when: ansible_os_family=="Debian"
      notify: uninstall apache2
  
  handlers:
    - name: uninstall httpd
      service:
        name: httpd
        state: absent

    - name: uninstall apache2
      service:
        name: apache2
        state: absent
