---

- name: install apache 2 on ubuntu
  hosts: Dbservers
  become: true
  tasks:
    - name: install apache module
      apt:
        name: apache2
        state: present
    
    - name: start apache2 service
      service:
        name: apache2
        state: started