---

- name: this playbook is to create file
  hosts: all
  become: true
  tasks:
    - name: file module
      file:   #this is the file modue
        state: absent  # this is the action to be performed. 
        path: /home/ansadmin/filebyAnsible.yaml   # here we are removing the fikebyAnsible.yaml file using absent stete

# we can do the same to directory as well. just change the path 