---
- name: yum package
  hosts: Webservers
  become: yes
  tasks:
    - name: install 
      yum:
        name: git
        state: present

# to run this playbook: ansible-playbook -i hosts yumModule.yaml